package projetosistemasw.view;

import br.com.controle.visao.GerenteDeImagens;
import javax.swing.JOptionPane;
import projetosistemasw.dao.TesteUsuarioDAO;
import projetosistemasw.model.TesteUsuario;
/*
 *
 * @author danie
 */
public class TelaCadastro extends javax.swing.JFrame {
    //conecta as classes do projeto na TelaCadastro
    GerenteDeImagens gerenteDeImagens = new GerenteDeImagens();
    TesteUsuarioDAO tud = new TesteUsuarioDAO();
    TesteUsuario tes = new TesteUsuario();
    

    public TelaCadastro() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastro = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblEstados = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        cmbEstados = new javax.swing.JComboBox<>();
        lblCep = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        jrbFeminino = new javax.swing.JRadioButton();
        jrbMasculino = new javax.swing.JRadioButton();
        lblSenha = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblRepitaSenha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        pswRepitaSenha = new javax.swing.JPasswordField();
        btnProcurar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        pnlFoto = new javax.swing.JPanel();
        lblFotoPerfil = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        pnlCadastro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCadastro.setLayout(null);

        lblEmail.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblEmail.setText("E-mail");
        pnlCadastro.add(lblEmail);
        lblEmail.setBounds(400, 40, 60, 20);

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNome.setBorder(null);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        pnlCadastro.add(txtNome);
        txtNome.setBounds(20, 60, 340, 20);

        lblSexo.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblSexo.setText("Sexo");
        pnlCadastro.add(lblSexo);
        lblSexo.setBounds(390, 110, 50, 30);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        pnlCadastro.add(txtEmail);
        txtEmail.setBounds(400, 60, 400, 20);

        lblNome.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblNome.setText("Nome");
        pnlCadastro.add(lblNome);
        lblNome.setBounds(20, 40, 60, 20);

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefone.setBorder(null);
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        pnlCadastro.add(txtTelefone);
        txtTelefone.setBounds(20, 130, 150, 20);

        lblNumero.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblNumero.setText("Nº");
        pnlCadastro.add(lblNumero);
        lblNumero.setBounds(460, 170, 30, 20);

        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCelular.setBorder(null);
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        pnlCadastro.add(txtCelular);
        txtCelular.setBounds(210, 130, 140, 20);

        lblTelefone.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone");
        pnlCadastro.add(lblTelefone);
        lblTelefone.setBounds(20, 110, 80, 20);

        lblBairro.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblBairro.setText("Bairro");
        pnlCadastro.add(lblBairro);
        lblBairro.setBounds(250, 230, 60, 20);

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEndereco.setBorder(null);
        pnlCadastro.add(txtEndereco);
        txtEndereco.setBounds(20, 190, 410, 20);

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumero.setBorder(null);
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        pnlCadastro.add(txtNumero);
        txtNumero.setBounds(460, 190, 90, 20);

        lblEndereco.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblEndereco.setText("Endereço");
        pnlCadastro.add(lblEndereco);
        lblEndereco.setBounds(20, 170, 80, 20);

        txtComplemento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtComplemento.setBorder(null);
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        pnlCadastro.add(txtComplemento);
        txtComplemento.setBounds(20, 250, 210, 20);

        lblCidade.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblCidade.setText("Cidade");
        pnlCadastro.add(lblCidade);
        lblCidade.setBounds(150, 290, 70, 20);

        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBairro.setBorder(null);
        pnlCadastro.add(txtBairro);
        txtBairro.setBounds(250, 250, 240, 20);

        lblComplemento.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblComplemento.setText("Complemento");
        pnlCadastro.add(lblComplemento);
        lblComplemento.setBounds(20, 230, 130, 20);

        txtCep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCep.setBorder(null);
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });
        pnlCadastro.add(txtCep);
        txtCep.setBounds(20, 310, 110, 20);

        lblEstados.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblEstados.setText("Estado");
        pnlCadastro.add(lblEstados);
        lblEstados.setBounds(420, 290, 60, 20);

        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCidade.setBorder(null);
        pnlCadastro.add(txtCidade);
        txtCidade.setBounds(150, 310, 260, 20);

        lblNascimento.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblNascimento.setText("Nascimento: dd/mm/aa");
        pnlCadastro.add(lblNascimento);
        lblNascimento.setBounds(20, 410, 200, 20);

        cmbEstados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF" }));
        pnlCadastro.add(cmbEstados);
        cmbEstados.setBounds(480, 300, 80, 30);

        lblCep.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblCep.setText("Cep");
        pnlCadastro.add(lblCep);
        lblCep.setBounds(20, 290, 40, 20);

        txtRG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRG.setBorder(null);
        pnlCadastro.add(txtRG);
        txtRG.setBounds(20, 370, 150, 20);

        lblRG.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblRG.setText("RG");
        pnlCadastro.add(lblRG);
        lblRG.setBounds(20, 350, 40, 20);

        txtCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCPF.setBorder(null);
        pnlCadastro.add(txtCPF);
        txtCPF.setBounds(200, 370, 150, 20);

        lblCelular.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblCelular.setText("Celular");
        pnlCadastro.add(lblCelular);
        lblCelular.setBounds(210, 108, 70, 20);

        jrbFeminino.setBackground(new java.awt.Color(255, 255, 255));
        jrbFeminino.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jrbFeminino.setText("Feminino");
        jrbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFemininoActionPerformed(evt);
            }
        });
        pnlCadastro.add(jrbFeminino);
        jrbFeminino.setBounds(440, 100, 110, 20);

        jrbMasculino.setBackground(new java.awt.Color(255, 255, 255));
        jrbMasculino.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jrbMasculino.setText("Masculino");
        jrbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMasculinoActionPerformed(evt);
            }
        });
        pnlCadastro.add(jrbMasculino);
        jrbMasculino.setBounds(440, 130, 110, 20);

        lblSenha.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblSenha.setText("Senha");
        pnlCadastro.add(lblSenha);
        lblSenha.setBounds(220, 410, 60, 20);

        txtNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNascimento.setBorder(null);
        txtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascimentoActionPerformed(evt);
            }
        });
        pnlCadastro.add(txtNascimento);
        txtNascimento.setBounds(20, 430, 120, 20);

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlCadastro.add(btnSalvar);
        btnSalvar.setBounds(20, 480, 150, 50);

        lblCPF.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblCPF.setText("CPF");
        pnlCadastro.add(lblCPF);
        lblCPF.setBounds(200, 350, 40, 22);

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario.setBorder(null);
        pnlCadastro.add(txtUsuario);
        txtUsuario.setBounds(370, 370, 160, 20);

        lblRepitaSenha.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblRepitaSenha.setText("Repita Senha");
        pnlCadastro.add(lblRepitaSenha);
        lblRepitaSenha.setBounds(410, 410, 110, 20);

        lblUsuario.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        lblUsuario.setText("Usuário");
        pnlCadastro.add(lblUsuario);
        lblUsuario.setBounds(370, 350, 70, 20);

        pswSenha.setBorder(null);
        pnlCadastro.add(pswSenha);
        pswSenha.setBounds(220, 430, 170, 20);

        pswRepitaSenha.setBorder(null);
        pnlCadastro.add(pswRepitaSenha);
        pswRepitaSenha.setBounds(410, 430, 170, 20);

        btnProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosistemasw/imgs/icons8-procurar-pasta-45.png"))); // NOI18N
        btnProcurar.setContentAreaFilled(false);
        btnProcurar.setDefaultCapable(false);
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        pnlCadastro.add(btnProcurar);
        btnProcurar.setBounds(590, 380, 50, 40);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosistemasw/imgs/icons8-excluir-45.png"))); // NOI18N
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlCadastro.add(btnExcluir);
        btnExcluir.setBounds(660, 370, 40, 60);
        pnlCadastro.add(jSeparator2);
        jSeparator2.setBounds(20, 80, 340, 10);
        pnlCadastro.add(jSeparator1);
        jSeparator1.setBounds(400, 80, 400, 10);
        pnlCadastro.add(jSeparator3);
        jSeparator3.setBounds(20, 150, 150, 10);
        pnlCadastro.add(jSeparator4);
        jSeparator4.setBounds(210, 150, 140, 10);
        pnlCadastro.add(jSeparator5);
        jSeparator5.setBounds(20, 210, 410, 10);
        pnlCadastro.add(jSeparator6);
        jSeparator6.setBounds(460, 210, 90, 10);
        pnlCadastro.add(jSeparator7);
        jSeparator7.setBounds(20, 270, 210, 10);
        pnlCadastro.add(jSeparator8);
        jSeparator8.setBounds(250, 270, 240, 10);
        pnlCadastro.add(jSeparator9);
        jSeparator9.setBounds(20, 330, 110, 10);
        pnlCadastro.add(jSeparator10);
        jSeparator10.setBounds(150, 330, 260, 10);
        pnlCadastro.add(jSeparator12);
        jSeparator12.setBounds(20, 390, 150, 10);
        pnlCadastro.add(jSeparator13);
        jSeparator13.setBounds(200, 390, 150, 10);
        pnlCadastro.add(jSeparator14);
        jSeparator14.setBounds(370, 390, 160, 10);
        pnlCadastro.add(jSeparator15);
        jSeparator15.setBounds(20, 450, 120, 10);
        pnlCadastro.add(jSeparator16);
        jSeparator16.setBounds(220, 450, 170, 10);
        pnlCadastro.add(jSeparator17);
        jSeparator17.setBounds(410, 450, 170, 10);

        pnlFoto.setBackground(new java.awt.Color(255, 255, 255));
        pnlFoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara Light", 0, 18))); // NOI18N
        pnlFoto.setForeground(new java.awt.Color(255, 255, 255));
        pnlFoto.setLayout(null);

        lblFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosistemasw/imgs/login2.png"))); // NOI18N
        pnlFoto.add(lblFotoPerfil);
        lblFotoPerfil.setBounds(10, 30, 200, 230);

        pnlCadastro.add(pnlFoto);
        pnlFoto.setBounds(590, 100, 220, 270);

        getContentPane().add(pnlCadastro);
        pnlCadastro.setBounds(0, 0, 830, 570);

        setSize(new java.awt.Dimension(846, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void jrbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbFemininoActionPerformed

    private void jrbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMasculinoActionPerformed

    private void txtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascimentoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    if(pswSenha.getText().equals(pswRepitaSenha.getText())){
            
        tes.setNome(txtNome.getText());                                //1
        tes.setEmail(txtEmail.getText());                              //2
        tes.setTelefone(txtTelefone.getText());                        //3
        tes.setCelular(txtCelular.getText());                          //4
        tes.setEndereco(txtEndereco.getText());                        //5
        tes.setNumero(txtNumero.getText());                            //6
        tes.setComplemento(txtComplemento.getText());                  //7
        tes.setBairro(txtBairro.getText());                            //8
        tes.setCep(txtCep.getText());                                  //9
        tes.setCidade(txtCidade.getText());                            //10
        tes.setEstados(cmbEstados.getSelectedItem().toString());       //11
        tes.setRG(txtRG.getText());                                    //12
        tes.setCPF(txtCPF.getText());                                  //13
        tes.setUsuario(txtUsuario.getText());                          //14
        tes.setNascimento(txtNascimento.getText());                    //15
        tes.setSenha(pswSenha.getText());                              //16
        tes.setImagem(gerenteDeImagens.getUrlImagem());
        if (jrbMasculino.isSelected() == false && jrbFeminino.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Selecione o campo sexo do formulario");    
        } else if (jrbMasculino.isSelected()) {                                   //17
            tes.setSexo("Masculino");
        } else if (jrbFeminino.isSelected()) {
            tes.setSexo("feminino");
        }

        tud.salvar(tes);
        JOptionPane.showMessageDialog(null,"Cadastro criado com sucesso");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        gerenteDeImagens.escolherImagem(lblFotoPerfil);

    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

       lblFotoPerfil.setIcon(new javax.swing.ImageIcon( "C:\\Users\\danie\\Desktop\\projetosistemasw-master\\src\\projetosistemasw\\imgs\\login2.png" ));
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbEstados;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JRadioButton jrbFeminino;
    private javax.swing.JRadioButton jrbMasculino;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstados;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRepitaSenha;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlFoto;
    private javax.swing.JPasswordField pswRepitaSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
