/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetosistemasw.view;

import br.com.controle.visao.GerenteDeImagens;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import projetosistemasw.dao.TesteUsuarioDAO;
import projetosistemasw.model.TesteRelatorio;
import projetosistemasw.model.TesteUsuario;

/**
 *
 * @author danie
 */
public class TelaRelatorio extends javax.swing.JFrame {

    //conecta o DAO a está tela
    TesteUsuarioDAO tud = new TesteUsuarioDAO();
    TesteRelatorio tre = new TesteRelatorio();
    TesteUsuario tu = new TesteUsuario();
    GerenteDeImagens gerenteDeImagens = new GerenteDeImagens();

    public TelaRelatorio() {
        initComponents();
        btnGerarRelatorio.setVisible(false);
        btnExcluirRelatorio1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalRelatorio = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblRNome = new javax.swing.JLabel();
        lblRCPF = new javax.swing.JLabel();
        txtRNome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtRCPF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        lblRCausa = new javax.swing.JLabel();
        lblRData = new javax.swing.JLabel();
        lblRLocal = new javax.swing.JLabel();
        txtRData = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtRLocal = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtRCausa = new javax.swing.JTextField();
        txtRCodigo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblRCausa1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalvarRelatorio = new javax.swing.JButton();
        btnGerarRelatorio = new javax.swing.JButton();
        btnconsultarRelatorio1 = new javax.swing.JButton();
        btnExcluirRelatorio1 = new javax.swing.JButton();
        pnlFoto = new javax.swing.JPanel();
        lblFotoPerfilRelatorio = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        pnlPrincipalRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipalRelatorio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlPrincipalRelatorio.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do empregado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        jPanel2.setLayout(null);

        lblRNome.setFont(new java.awt.Font("Candara Light", 0, 15)); // NOI18N
        lblRNome.setText("Nome");
        jPanel2.add(lblRNome);
        lblRNome.setBounds(20, 110, 50, 20);

        lblRCPF.setFont(new java.awt.Font("Candara Light", 0, 15)); // NOI18N
        lblRCPF.setText("CPF");
        jPanel2.add(lblRCPF);
        lblRCPF.setBounds(20, 40, 50, 20);

        txtRNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRNome.setBorder(null);
        txtRNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRNomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRNomeMousePressed(evt);
            }
        });
        txtRNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRNomeActionPerformed(evt);
            }
        });
        txtRNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRNomeKeyPressed(evt);
            }
        });
        jPanel2.add(txtRNome);
        txtRNome.setBounds(20, 130, 350, 20);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 150, 350, 10);

        txtRCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRCPF.setBorder(null);
        txtRCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtRCPFMouseExited(evt);
            }
        });
        jPanel2.add(txtRCPF);
        txtRCPF.setBounds(20, 60, 180, 20);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(20, 80, 180, 10);

        pnlPrincipalRelatorio.add(jPanel2);
        jPanel2.setBounds(10, 70, 540, 180);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do acidente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        jPanel3.setLayout(null);

        lblRCausa.setFont(new java.awt.Font("Candara Light", 0, 15)); // NOI18N
        lblRCausa.setText("Causa");
        jPanel3.add(lblRCausa);
        lblRCausa.setBounds(20, 190, 50, 20);

        lblRData.setFont(new java.awt.Font("Candara Light", 0, 15)); // NOI18N
        lblRData.setText("Data");
        jPanel3.add(lblRData);
        lblRData.setBounds(20, 90, 40, 20);

        lblRLocal.setFont(new java.awt.Font("Candara Light", 0, 15)); // NOI18N
        lblRLocal.setText("Local");
        jPanel3.add(lblRLocal);
        lblRLocal.setBounds(20, 140, 32, 20);

        txtRData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRData.setBorder(null);
        jPanel3.add(txtRData);
        txtRData.setBounds(20, 110, 140, 20);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(20, 130, 140, 10);

        txtRLocal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRLocal.setBorder(null);
        jPanel3.add(txtRLocal);
        txtRLocal.setBounds(20, 160, 650, 20);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(20, 180, 650, 10);
        jPanel3.add(jSeparator5);
        jSeparator5.setBounds(20, 230, 650, 10);

        txtRCausa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRCausa.setBorder(null);
        jPanel3.add(txtRCausa);
        txtRCausa.setBounds(20, 210, 650, 20);

        txtRCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRCodigo.setBorder(null);
        jPanel3.add(txtRCodigo);
        txtRCodigo.setBounds(20, 60, 290, 20);
        jPanel3.add(jSeparator6);
        jSeparator6.setBounds(20, 80, 290, 10);

        lblRCausa1.setFont(new java.awt.Font("Candara Light", 0, 15)); // NOI18N
        lblRCausa1.setText("Codigo");
        jPanel3.add(lblRCausa1);
        lblRCausa1.setBounds(20, 40, 50, 20);

        pnlPrincipalRelatorio.add(jPanel3);
        jPanel3.setBounds(10, 300, 700, 250);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Registro de acidentes");
        pnlPrincipalRelatorio.add(jLabel4);
        jLabel4.setBounds(290, 10, 230, 30);

        btnSalvarRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvarRelatorio.setText("Salvar");
        btnSalvarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarRelatorioActionPerformed(evt);
            }
        });
        pnlPrincipalRelatorio.add(btnSalvarRelatorio);
        btnSalvarRelatorio.setBounds(20, 580, 110, 50);

        btnGerarRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGerarRelatorio.setText("Gerar relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });
        pnlPrincipalRelatorio.add(btnGerarRelatorio);
        btnGerarRelatorio.setBounds(280, 580, 150, 50);

        btnconsultarRelatorio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnconsultarRelatorio1.setText("Consultar");
        btnconsultarRelatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarRelatorio1ActionPerformed(evt);
            }
        });
        pnlPrincipalRelatorio.add(btnconsultarRelatorio1);
        btnconsultarRelatorio1.setBounds(150, 580, 110, 50);

        btnExcluirRelatorio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluirRelatorio1.setText("Excluir");
        btnExcluirRelatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirRelatorio1ActionPerformed(evt);
            }
        });
        pnlPrincipalRelatorio.add(btnExcluirRelatorio1);
        btnExcluirRelatorio1.setBounds(450, 580, 110, 50);

        pnlFoto.setBackground(new java.awt.Color(255, 255, 255));
        pnlFoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 20))); // NOI18N
        pnlFoto.setForeground(new java.awt.Color(255, 255, 255));
        pnlFoto.setLayout(null);

        lblFotoPerfilRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblFotoPerfilRelatorio.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Pictures\\fotos\\download (2).jpg")); // NOI18N
        pnlFoto.add(lblFotoPerfilRelatorio);
        lblFotoPerfilRelatorio.setBounds(10, 30, 180, 200);

        pnlPrincipalRelatorio.add(pnlFoto);
        pnlFoto.setBounds(570, 50, 210, 250);

        getContentPane().add(pnlPrincipalRelatorio);
        pnlPrincipalRelatorio.setBounds(0, 0, 800, 670);

        setSize(new java.awt.Dimension(816, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        //gerar relatrorio PDF
        if (campos() == true) {
            JOptionPane.showMessageDialog(null, "preencha os campos");
            txtRCodigo.requestFocus();
        } else {
            if (tud.GRpdf(tre, tu) == true) {

                Document documentoPDF = new Document();
                try {
                    //cria um instacia pdf e da o nome ao arquivo
                    PdfWriter.getInstance(documentoPDF, new FileOutputStream("C:\\Users\\Public\\Documents\\PDF_Relatorios.pdf"));
                    //abre o arquivo
                    documentoPDF.open();
                    //setar o tamanho do documento
                    documentoPDF.setPageSize(PageSize.A4);
                    //adicionar o primeiro paragrafo
                    documentoPDF.add(new Paragraph("Relatorio do acidente"));
                    Image image = Image.getInstance(tu.getImagem() + "");
                    image.scaleToFit(400, 200);
                    documentoPDF.add(image);
                    documentoPDF.add(new Paragraph("Codigo do acidente: " + txtRCodigo.getText() + "\n"));
                    documentoPDF.add(new Paragraph("\n"));
                    documentoPDF.add(new Paragraph(tre.getTxtRNome() + " portador do RG: " + tu.getRG() + " e do CPF: " + tre.getTxtRCPF() + ", nascido em " + tu.getNascimento() + "\nsituado no endereço " + tu.getEndereco() + " Nº: " + tu.getNumero()
                            + " bairro: " + tu.getBairro() + " cep:" + tu.getCep() + " cidade: " + tu.getCidade() + " estado:" + tu.getEstados() + "\n" + "que foi vitima em decorrencia do acidente ocorrido no dia: " + tre.getTxtRData() + ", e localizado no(a): " + tre.getTxtRLocal()
                            + ", em consequência de: " + tre.getTxtRCausa()));

                    JOptionPane.showMessageDialog(null, "Relatório feito com sucesso");

                } catch (DocumentException e) {
                    e.printStackTrace();

                } catch (IOException io) {
                    io.printStackTrace();
                } finally {
                    documentoPDF.close();
                }
            }
        }
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void btnSalvarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarRelatorioActionPerformed
        if (campos() == true) {
            JOptionPane.showMessageDialog(null, "preencha os campos");
            txtRCodigo.requestFocus();

        } else {

            if (tud.puxar(this) == true) {

                //Vai gravar  as info no BD do ocorrido
                tre.setTxtRCodigo(Integer.parseInt(txtRCodigo.getText()));
                tre.setTxtRNome(txtRNome.getText());
                tre.setTxtRCPF(txtRCPF.getText());
                tre.setTxtRData(txtRData.getText());
                tre.setTxtRLocal(txtRLocal.getText());
                tre.setTxtRCausa(txtRCausa.getText());
                int resultado;
                resultado = tud.salvarDadosR(tre);

                if (resultado == 1062) {

                    JOptionPane.showMessageDialog(null, "Essa matricula já está cadastrada");
                } else if (resultado == 1) {

                    JOptionPane.showMessageDialog(null, "Funcionário salvo com sucesso");
                    btnGerarRelatorio.setVisible(true);
                    btnExcluirRelatorio1.setVisible(true);
                } else {

                    JOptionPane.showMessageDialog(null, "Erro na gravação");
                }
            } else {

                //caso não sejá encontrado o nome e/ou CPF digitado na TelaRelaorio no banco de dados
                JOptionPane.showMessageDialog(null, "Nome e/ou CPF inválidos");
                txtRNome.requestFocus();
            }

        }
    }//GEN-LAST:event_btnSalvarRelatorioActionPerformed

    private void txtRNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRNomeActionPerformed

    }//GEN-LAST:event_txtRNomeActionPerformed

    private void txtRNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRNomeMouseClicked
        //vai puxar o nome da pessoa com o cpf
        fo();

    }//GEN-LAST:event_txtRNomeMouseClicked

    private void btnconsultarRelatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarRelatorio1ActionPerformed
        // vai consultar codigo
        if ("".equals(txtRCodigo.getText())) {
            JOptionPane.showMessageDialog(null, "preencha os campos");
        } else {
            fo();
            tre.setTxtRCodigo(Integer.parseInt(txtRCodigo.getText()));
            tre.setTxtRCPF(txtRCPF.getText());
            if (tud.GRpdf(tre, tu) == true) {
                txtRNome.setText(tu.getNome());
                lblFotoPerfilRelatorio.setIcon(new javax.swing.ImageIcon(tu.getImagem()));

            }
            if (tud.puxarCodigo(tre) == true) {
                txtRNome.setText(tre.getTxtRNome());
                txtRCPF.setText(tre.getTxtRCPF());
                txtRData.setText(tre.getTxtRData());
                txtRLocal.setText(tre.getTxtRLocal());
                txtRCausa.setText(tre.getTxtRCausa());
                btnGerarRelatorio.setVisible(true);
                btnExcluirRelatorio1.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Codigo inválido");
                txtRCodigo.requestFocus();
            }
        }
    }//GEN-LAST:event_btnconsultarRelatorio1ActionPerformed

    private void btnExcluirRelatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirRelatorio1ActionPerformed
        tre.setTxtRCodigo(Integer.parseInt(txtRCodigo.getText()));
        if (tud.excluir(tre) == true) {
            JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possivel excluir os dados");
        }

    }//GEN-LAST:event_btnExcluirRelatorio1ActionPerformed

    private void txtRNomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRNomeMousePressed

    }//GEN-LAST:event_txtRNomeMousePressed

    private void txtRNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRNomeKeyPressed


    }//GEN-LAST:event_txtRNomeKeyPressed

    private void txtRCPFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRCPFMouseExited

    }//GEN-LAST:event_txtRCPFMouseExited
    private boolean campos() {
        if (("".equals(txtRCodigo.getText())) || ("".equals(txtRData.getText())) || ("".equals(txtRLocal.getText())) || ("".equals(txtRCausa.getText()))) {
            return true;
        } else {
            return false;
        }
    }

    private void fo() {
        //vai puxar o nome da pessoa com o cpf
        tre.setTxtRCPF(txtRCPF.getText());
        if (tud.GRpdf(tre, tu) == true) {
            txtRNome.setText(tu.getNome());
            lblFotoPerfilRelatorio.setIcon(new javax.swing.ImageIcon(tu.getImagem()));

        }}
        /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirRelatorio1;
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JButton btnSalvarRelatorio;
    private javax.swing.JButton btnconsultarRelatorio1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblFotoPerfilRelatorio;
    private javax.swing.JLabel lblRCPF;
    private javax.swing.JLabel lblRCausa;
    private javax.swing.JLabel lblRCausa1;
    private javax.swing.JLabel lblRData;
    private javax.swing.JLabel lblRLocal;
    private javax.swing.JLabel lblRNome;
    private javax.swing.JPanel pnlFoto;
    private javax.swing.JPanel pnlPrincipalRelatorio;
    public javax.swing.JTextField txtRCPF;
    private javax.swing.JTextField txtRCausa;
    public javax.swing.JTextField txtRCodigo;
    private javax.swing.JTextField txtRData;
    private javax.swing.JTextField txtRLocal;
    public javax.swing.JTextField txtRNome;
    // End of variables declaration//GEN-END:variables
}
